openapi: 3.0.0
info:
  title: Human-In-The-Loop API
  version: "1.0"
servers:
  - url: https://human-in-the-loop.groff.workers.dev
paths:
  /add-message:
    post:
      summary: Add a message to the queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
      responses:
        "200":
          description: Message successfully sent to the queue
        "400":
          description: Invalid request body
  /get-oldest-message:
    get:
      summary: Get the oldest message awaiting review
      responses:
        "200":
          description: Successfully fetched the oldest message
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  content:
                    type: string
                  approvalStatus:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        "404":
          description: No messages awaiting review
  /update-message-status/{messageId}:
    put:
      summary: Update a message's approval status
      parameters:
        - in: path
          name: messageId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - approved
                    - denied
      responses:
        "200":
          description: Message status updated successfully
        "400":
          description: Invalid request parameters
  /get-reviewed-messages:
    get:
      summary: Get the latest 10 reviewed messages
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number for pagination
      responses:
        "200":
          description: Successfully fetched the latest reviewed messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    content:
                      type: string
                    approvalStatus:
                      type: string
                      enum:
                        - approved
                        - denied
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
components:
  securitySchemes: {}
